class Ozellikler {
  static const String Uygulama_Adi = "Burç Kataloğu";
  static const List<String> Burc_Adlari = [
    "Koç",
        "Boğa",
        "İkizler",
        "Yengeç",
        "Aslan",
        "Başak",
        "Terazi",
        "Akrep",
        "Yay",
        "Oğlak",
        "Kova",
        "Balık"
  ];

  static const List<String> Burc_Tarihleri = [
    "21 Mart-20 Nisan",
    "21 Nisan-21 Mayıs",
    "22 Mayıs-22 Haziran",
    "23 Haziran-22 Temmuz",
    "23 Temmuz-22 Ağustos",
    "23 Ağustos-22 Eylül",
    "23 Eylül-22 Ekim",
    "23 Ekim-21 Kasım",
    "22 Kasım-21 Aralık",
    "22 Aralık-21 Ocak",
    "22 Ocak-19 Şubat",
    "20 Şubat-20 Mart"
  ];
  static const List<List<String>> Burc_Ozellikleri = [
[
        "Koç",
        "Ateş",
        "Kardinal",
        "Mars (savaş ve enerji gezegeni)",
        "Kırmızı",
        "Salı",
        "1,9",
        "Opal, Turmalin, Yakut, Jasper, Akik",
        "Enerjik, cesaret verici, durdurulamaz, cesur, adanmış, kahraman, şefkatli",
        "Kibirli, benmerkezci, itkisel, buyurgan, inatçı, umursamaz, kıskanç",
        "Rekabetçi oyunlar, rahat giysiler, yolculuk, tartışmak, kendini şaşırtıcı sözlü ve fiziksel kahramanlıklarla ifade etmek, liderlik, fiziksel güçlükler, spor",
        "Görmezden gelinmek, dar alanlar, kaybetmek, “hayır” kelimesi, hareketsizlik, gecikmeler",
        "Bir numara olmak",
        "Cesur, kararlı, öz güvenli, coşkulu, iyimser, dürüst, tutkulu olmaları",
        "Sabırsız, dengesiz, çabuk öfkelenen, saldırgan olmaları"],

        ["Boğa",
        "Toprak",
        "Sabit",
        "Venüs (güzelliğin ve aşkın gezegeni)",
        "Yeşil,Pembe",
        "Cuma,Pazartesi",
        ",4",
        "Turkuaz taşı, Topaz Taşı, Pembe Kuvars, Safir, Yeşim",
        "Sabırlı, düzenli, yardımcı, romantik, özenli, adanmış",
        "Fazla hoşgörülü, inatçı, tembel, fazla ihtiyatlı",
        "Fotoğraf, dağlar, güzel müzik, gurme yemek, yemek pişirmek, bahçecilik, romans, kaliteli giysiler",
        "Acele ettirilmek, parayı israf etmek, kirli şeyler, oteller, ani değişiklikler, engeller, güvensizlik",
        "Her şeyin en iyisine sahip olmak",
        "Güvenilir, sabırlı, pratik, adanmış, sorumluluk sahibi, stabil olmaları",
        "İnatçı, sahiplenici, tavizsiz olmaları"],

        ["İkizler",
        "Hava",
        "Değişken",
        "Merkür (iletişim ve haberleşmenin gezegeni)",
        "Açık yeşil, sarı",
        "Çarşamba",
        "5, 7",
        "Akuamarin, Akik, Topaz, Sitrin, Turmalin",
        "Etkileyici, özgün, iş bilen, alımlı, akıllı, maceracı",
        "Vesveseli, dengesiz, iki yüzlü, yargılayıcı, depresif",
        "Müzik, kitaplar, dergiler, sohbet etmek, kısa gezintiler",
        "Yalnız olmak, sınırlandırılmak, tekrar ve rutin, dar görüşlü insanlar, geleneksel moda, otorite figürleri, sessizlik",
        "Tüm cevapları bulmak",
        "Kibar, sevecen, meraklı, uyumlu, yeni fikirleri çabucak öğrenebilir olmaları",
        "Gergin, tutarsız ve kararsız olmaları"],


        ["Yengeç",
        "Su",
        "Kardinal (öncü)",
        "Ay (duyguları ve ruhsal durumları yöneten gök cismi)",
        "Beyaz",
        "Pazartesi, Perşembe",
        "2,3",
        "Akuamarin, Ay taşı, Kuvars kristali, Safir Taşı, Zümrüt",
        "Yardımsever, sabırlı, merhametli, anaç, romantik, yaratıcı",
        "Dedikoducu, burnu havada, ketum, aşırı duyarlı, fazla rekabetçi",
        "Gurme yemekler, salon sporları, ev partileri, çocuklar, müze ve sanat galeriler, evde yapılan hobiler, denize girmek, sevdiklerine yardım etmek",
        "Pejmürde giysiler, uluorta konuşmak, acele ettirilmek, yabancı insanlar, özel hayatını anlatmak",
        "Arkadaşlarına ve ailelerine göz kulak olmak",
        "Sebatkâr, hayal gücü yüksek, sadık, duygusal, sempatik, ikna gücü yüksek olmaları",
        "Bunalımlı, kötümser, şüpheci, manipülatif olmaları"],


        ["Aslan",
        "Ateş",
        "Sabit",
        "Güneş",
        "Altın sarısı, sarı, turuncu",
        "Pazar",
        "1, 3",
        "Akik, Kehribar, Oniks, Topaz taşı, Kaplangözü",
        "Cesur, kibar, cömert, sadık, koruyucu, dobra, eğlenceli",
        "Küstah, müsrif, özensiz, taş kalpli, kıskanç, saldırgan",
        "Kameralar, şarkı söylemek, yakınlık kurmak, iltifat, güzel kıyafetler, tiyatro, pahalı şeyler, tatiller",
        "Görmezden gelinmek, yavan yemekler, yalnız kalmak, vedalar, kral-kraliçe muamelesi görmemek",
        "Dünyayı yönetmek",
        "Yaratıcı, tutkulu, cömert, cana yakın, neşeli, esprili olmaları",
        "Küstah, inatçı, benmerkezci, tembel, katı olmaları"],


       ["Bakire kadın",
        "Toprak",
        "Değişken",
        "Merkür (iletişim gezegeni)",
        "Gri, bej, açık sarı",
        "Çarşamba",
        "5, 14",
        "Akik, Kehribar, Jasper, Turmalin, Yeşim",
        "Adanmış, becerikli, yardımsever, çalışkan, hazırcevap, pratik",
        "Vaaz verme meraklısı, kendi kendine zarar verme, kendine acıma, şekilci, eleştirel",
        "Bilgisayarlar, dergiler, uzun banyolar, konserler, çocukluk arkadaşları, hayvanlar, sağlıklı yemekler, kitaplar, doğa, temizlik",
        "Tembel ya da kaba insanlar, evden ayrılmak, yardım istemek",
        "Kahraman olmak",
        "Sadık, analitik, nazik, çalışkan, pratik olmaları",
        "Utangaç, endişeli, aşırı yargılayıcı olmaları"],

        ["Adalet terazisi",
        "Hava",
        "Kardinal",
        "Venüs (güzelliğin, lüksün ve aşkın gezegeni)",
        "Pembe, yeşil",
        "Cuma",
        "4, 6",
        "Yeşim, Topaz, Pembe Kuvars, Turmalin, Akuvamarin",
        "Çekici, sevimli, adil, cana yakın, paylaşımcı, romantik",
        "Faydasız, kararsız, aşırı duygusal, manipülatif, şımarık, kuruntulu",
        "Büyük konserler, şiir, pahalı mücevherler, tasarım giysiler, iyi yemek, uyum, nezaket, gezmek",
        "Donuk ya da pratik insanlar, zorbalık, bir karar vermeye zorlanmak, “belki”ler, şiddet, adaletsizlik, gevezelik, şekilcilik",
        "Sevmek ve sevilmek",
        "Dayanışmacı, diplomat, zarif, tarafsız, sosyal olmaları",
        "Kararsız olmaları, çatışmadan kaçmaları, kendilerine acımaları"],

       [ "Akrep",
        "Su",
        "Sabit",
        "Plüton (gücün ve yenilenmenin gezegeni)",
        "Kırmızı, Bordo, Siyah",
        "Salı",
        "8, 11, 18, 22",
        "Yakut, Opal, Lal",
        "Sabırlı, derinlemesine bilgi sahibi, disiplinli, dikkatli",
        "Kindar, asıl niyetini gizleyen, herkese karşı güvensiz",
        "Gizemlilik, tehlike havası, underground müzik, tıbbi bitkiler, lateks veya deri kıyafetler",
        "Basit insanlar, samimiyetsizlik, özel sorular, başkasının evinde yaşamak zorunda olmak",
        "Başkalarının hayatına dair her şeyi bilmek, tam bir kontrole sahip olmak.",
        "Güçlü beden, psikolojik direnç, sabır ve sükut",
        "Kıskançlık, pasif-agresif tutum, bencillik"],


        ["Okçu",
        "Ateş",
        "Değişken",
        "Jüpiter (şans ve ilerlemenin gezegeni)",
        "Mavi",
        "Perşembe",
        "3, 7, 9",
        "Safir, Lapis, Akik, Ametist, Lal",
        "Dürüst, tarafsız, iyimser, coşkulu, cesaretlendirici, adanmış",
        "Tartışmacı, umursamaz, tuhaf, vaaz verme meraklısı, nezaketsiz, kendinden çok emin",
        "Meydan okumak, flört etmek, evcil hayvanlar, yolculuk, gülmek, kitaplar, ilham veren öyküler, özgürlük, dışarıda olmak",
        "Önyargı, rutin, kurallar, can sıkkınlığı, meseleleri çok ciddiye almak, “yapamazsın” sözü, yapışkan insanlar, sınırlandırılmak, ayrıntılar",
        "Kuralları koymak",
        "Cömert, idealist, esprili olması",
        "Asla tutamayacağı sözler vermesi, çok sabırsız olması, kaba konuşması"],


       [ "Oğlak",
        "Toprak",
        "Kardinal (öncü)",
        "Satürn (disiplinin ve olgunluğun gezegeni)",
        "Kahverengi, siyah",
        "Cumartesi",
        "4, 8",
        "Turmalin, Zirkon, Yakut, Lal, Malahit",
        "Sadık, ailesine düşkün, çalışkan, adanmış, dürüst, korkusuz",
        "Kötümser, bağışlamaz, soğuk, maddiyatçı, burnu havada, umutsuz",
        "Kartvizitler, hedefler, iş unvanları, görev yapmak, aile, gelenek",
        "İstifa etmek, uluorta bağırmak, dikkatsizlik kaynaklı hatalar, kılavuz olmadan yolculuk yapmak, bir şeyi sırf yapmış olmak için yapmak",
        "Her ihtiyacı karşılamak",
        "Sorumluluk sahibi, disiplinli, otokontrollü olmaları, iyi yönetici olmaları",
        "Her şeyi bildiğini zanneden, bağışlamaz, küçümseyici olmaları"],


       [ "Kova",
        "Hava",
        "Sabit",
        "Uranüs (özgünlüğün gezegeni)",
        "Turuncu, gece mavisi, yeşil",
        "Pazar",
        "4, 7, 11,22, 29",
        "Yeşim, Obsidyen, Zirkon, Akuamarin, Ametist",
        "Bağımsız, özgün, insani, açık fikirli, adil, mantıklı",
        "Tavizsiz, gösterişçi, söz tutmama",
        "Arkadaşlarıyla eğlenmek, yardım etmek, entelektüel ortamlar, bilim-kurgu, bağımsız filmler",
        "Sınırlar, kırıcı sözler, yalnızlık, sıkıcı insanlar, karşıt görüşlü insanlar, adaletsizlik, ilgi manyağı insanlar",
        "Tamamen özgür olmak",
        "Özgün fikirler üretebilmek, hızlı öğrenmek, yeniliklere açık olmak",
        "Hevesinin çabuk kırılması, alıngan olmak, mesafeli olmak"],


        ["Balık",
        "Su",
        "Değişken",
        "Neptün (hayal gücünün gezegeni), Jüpiter (şans ve ilerlemenin gezegeni)",
        "Leylak, mor, eflatun, su yeşili",
        "Perşembe",
        "3, 9",
        "Akuamarin, Ay taşı, Ametist, Kuvars, Pembe Kuvars",
        "Romantik, yardımsever, bilge, rahatlatıcı, yaratıcı",
        "Saflık, kendine acıma, gerçeklikten kopukluk, kendine zarar verme, bağımlı",
        "Yalnız kalmak, uyumak, müzik dinlemek, şarkı söylemek, yazmak, aşık olmak, görsel medya, yüzmek, spiritüalizm, yürümek, burnunun dikine gitmek, içindeki karanlığı bastırmaya çalışmak, ağlamak",
        "Gerçeklik, gün ışığı, kötü tasarım, gürültülü müzik, ukalalık, eleştirilmek, her türlü gaddarlık, geçmişe takılıp kalmak, derdini anlatamamak ve anlaşılamamak, kale alınmamak, ruhsal ve fiziksel olarak kısıtlanmak",
        "Koşulsuz aşkı bulmak",
        "Şefkatli, sanatçı ruhlu, sezgisel, nazik, bilge",
        "Korkak, çabuk güvenen, hüzünlü olması, gerçeklikten uzak olması, kendini feda etmesi"]

  ];

  static const List<String> Burc_Ozellikleri_Basliklari = [

        "Sembol",
        "Element",
        "Nitelik",
        "Yönetici gezegen",
        "Renk",
        "Gün",
        "Uğurlu sayılar",
        "Uğurlu taşlar",
        "Olumlu özellikler",
        "Olumsuz özellikler",
        "En sevdiği şeyler",
        "Nefret ettiği şeyler",
        "Gizli tutkuları",
        "Güçlü yanları",
  ];
}
